// Customer guides, written for non-technical readers. Shown only in the platform owner's account (Customer Guides),
// where the owner can download them as PDFs and send them to subscribers and to their own MSP clients.

export interface GuideSection { id: string; title: string; intro?: string; steps?: string[]; bullets?: string[]; tip?: string }
export interface Guide { id: 'msp' | 'client'; title: string; subtitle: string; audience: string; sections: GuideSection[] }

export interface OmniContact { supportEmail: string; site: string }
export interface MspContact { name: string; phone?: string; email?: string; address?: string; portalUrl: string; hours?: string; emergency?: string; paymentTerms?: string }

/** User & Business Guide for MSPs who subscribe to (or buy) Omni TotalStack MSP. */
export function mspGuide(o: OmniContact): Guide {
  return {
    id: 'msp',
    title: 'Omni TotalStack MSP — User & Business Guide',
    subtitle: 'Everything you need to run your MSP from one place',
    audience: 'For MSP owners, admins, technicians and finance staff who use Omni',
    sections: [
      { id: 'welcome', title: '1. Welcome & how Omni is organized', intro: 'Omni is your whole MSP in one screen. The left menu has three parts:', bullets: ['Business Suite — clients, leads, proposals, finance, payroll, purchasing and QBRs (the business side).', 'Management Hub — sites, devices, discovery, patching, security, tickets, projects, inventory, documentation and tools (the technical side).', 'System — the Command Console, integrations, AI assistant, team logins, your plan and Admin & Branding.', 'Every page has a ? button at the top that explains it in plain English, and the search bar at the top finds any client, device, document, ticket, invoice or contract.'], tip: 'Lost? Click the ? button at the top of the screen to replay the guided tour.' },
      { id: 'start', title: '2. Getting started (first 30 minutes)', steps: ['Sign up at ' + o.site + '/signup, pick a plan and complete checkout. Your workspace is ready immediately.', 'Sign in. The Setup Wizard opens automatically: enter your company name, logo, colors, address, phone, labor rates and policies. These appear on your website, proposals, RFS, invoices and notices.', 'Go to Integrations and connect your tools — start with your RMM (Tactical RMM, NinjaOne or Atera), Huntress and Microsoft 365. Each card has step-by-step “How to get your keys” instructions.', 'Add your first client in Clients → New client (or create one from a lead).', 'Invite your team in Team & Client Logins.', 'Share your website link (Admin & Branding → Website & domain) on your business cards, Google profile and email signature.'], tip: 'Nothing breaks before you connect integrations — Omni shows sample data until your real data arrives.' },
      { id: 'home', title: '3. Command Center (home dashboard)', bullets: ['Monthly recurring revenue, open tickets, sites that are down, contracts expiring soon and unpaid invoices — at a glance.', 'Red always means “needs attention now” (down, expired or overdue). Amber means “soon”.', 'Click any card to jump to the details.'] },
      { id: 'command', title: '4. Command Console — type what you want done', intro: 'Instead of logging in to five different tools, type a command in plain English. Omni works out which tool does it, shows you the plan, and runs it only after you confirm.', bullets: ['Updates: “update windows 11 on all devices at Acme”, “patch status”.', 'Software (Chocolatey): “install chrome on all devices at Acme”, “upgrade all software on FRONTDESK-01”, “uninstall zoom on RECEPTION-02”.', 'Users (Entra ID / Microsoft 365): “add user Jane Doe jane@acme.com”, “disable user john@acme.com”, “enable user …”, “reset password …”, “delete user …”, “sign out user … everywhere”.', 'Users (on-premises Active Directory): add “in active directory”, e.g. “unlock user jdoe in active directory”.', 'Users (Webex): add “in webex”.', 'Devices: “reboot FRONTDESK-01”, “restart service spooler on ACME-DC01”, “run \"ipconfig /flushdns\" on all devices at Acme”, “gpupdate on all devices at Acme”, “connect to FRONTDESK-01” (RustDesk).', 'Servers & backups: “list vms”, “snapshot vm 101”, “restart vm 101” (Proxmox), “backup status” (Proxmox Backup Server / Synology), “nas status”, “what is down” (Uptime Kuma).', 'Tickets: “open ticket for Acme: printer offline” (Omni, Zammad, ITFlow), “open fusion ticket for Acme: internet down” (emails Fusion Connect).'], steps: ['Open Command Console in the left menu.', 'Type the command (or click an example) and press Enter.', 'Read the plan: what will happen, which tool does it, and any warnings.', 'Click Confirm & run. Deleting a user requires typing DELETE; restarting or running scripts on every device requires typing ALL.', 'Read the results. New or reset passwords are shown once — copy them right away.'], tip: 'Updates still follow your 15-day bug-free rule: anything still “soaking” is skipped and listed with the date it becomes eligible. Adding/deleting users, password resets and scripts are owner/admin only. Every command is saved in Admin → Audit log.' },
      { id: 'clients', title: '5. Clients', bullets: ['Each client is a folder: Overview, Sites, Contracts, Documents, Proposals & RFS, Network docs, Tickets, Projects, Billing and Roadmap / QBR.', 'Clients are grouped (Healthcare, Legal, Retail…) so similar clients stay together.', 'Contracts expiring within 30 days or already expired show in red.', 'Network docs are built automatically from your RMM, UniFi and network discovery; Users & groups come from Microsoft Graph (red rows = no MFA or not signed in for 45+ days).'] },
      { id: 'leads', title: '6. Leads & bookings', bullets: ['Everyone who fills in the form on your website appears here automatically, with any appointment they booked.', 'Click “AI call” and the AI voice assistant phones the lead, qualifies them and books a meeting (connect AI Voice in Integrations).', 'Click “Start proposal” to turn a lead into a client and build a proposal.'] },
      { id: 'proposals', title: '7. Proposals & RFS', steps: ['Proposals & RFS → New proposal.', 'Answer the needs questions (users, sites, compliance, current problems, budget).', 'Omni writes a formal proposal with three options (Good / Better / Best). Every option includes Huntress and covers both cybersecurity and networking.', 'Send it to the client. When they choose an option, click it to produce the RFS (Request for Service) PDF.', 'Signed proposals and RFS are saved in the client’s Documents automatically.'] },
      { id: 'finance', title: '8. Finance: invoices, payments and notices', bullets: ['QuickBooks panel — revenue, expenses, profit and money owed to you (connect QuickBooks Online in Integrations; it syncs both ways).', 'Invoice builder — drag services, hardware, billable ticket hours and project hours onto an invoice, then send it. Billable time from tickets and projects appears automatically.', 'Payments — clients pay from their portal by bank (ACH), card, Apple Pay or Google Pay through your Stripe account. Auto-pay and saved payment methods are supported; receipts are downloadable.', 'Financial health — MRR, ARR and profit per client and per service.', 'Non-payment notices — when an invoice passes its due date Omni prepares a Notice of Non-Payment with contractor, owner, prime contractor, description of work, amount owed and last date of service. Review it, then print or email it.'], tip: 'Have an attorney in your state review the non-payment notice wording once before you use it.' },
      { id: 'payroll', title: '9. Employees & payroll', bullets: ['Hours flow in from ticket and project time.', 'Review hours, PTO and pay, then click Run payroll — Gusto or QuickBooks Payroll handles taxes and direct deposit.'] },
      { id: 'procurement', title: '10. Procurement & inventory', bullets: ['Build a quote from vendor catalogs and see your profit instantly.', 'Turn it into a purchase order and track it; mark it Received and stock lands in Inventory while the vendor bill goes to Finance.', 'Assign inventory to a client and it appears in the invoice builder. Print QR labels to scan items into jobs.'] },
      { id: 'qbr', title: '11. IT strategy & QBRs', bullets: ['Each client gets health scores (security coverage, MFA, backups, warranties).', 'Plan and budget upgrades by quarter on the roadmap and present them at the quarterly business review.'] },
      { id: 'infra', title: '12. Sites, devices & outages', bullets: ['Sites & outages — every client location with live status: green online, amber degraded, red down (from UniFi, your RMM and Uptime Kuma).', 'All devices — every computer, server, firewall, switch, access point, printer and phone.', 'Site contracts & subscriptions — every renewal with its expiration date; red when expired or within 30 days.'] },
      { id: 'discovery', title: '13. Network discovery', steps: ['Network Discovery → download the Omni Agent.', 'Run it on any always-on computer at the client site (Windows, Mac or Linux with Python 3) — the page shows the exact command.', 'It scans the network (ping, ARP, common ports, SNMP) and reports devices back to Omni. New or risky devices are flagged.'] },
      { id: 'patching', title: '14. Patching & the weekly client email', bullets: ['Update pipeline — every update moves through Soaking → Approved → Deployed. An update is only approved after it has been bug-free for 15 days (you can change the number in Policy). A newly reported problem restarts the clock and blocks the update.', 'Weekly client email — every client gets an automatic weekly email listing what was updated and what is coming next. Pick the day and time in the Weekly client email tab.'] },
      { id: 'security', title: '15. Security (Huntress)', bullets: ['Agent coverage, incidents and subscription renewals per client from your Huntress partner account.', 'Identity gaps (no MFA, stale accounts) from Entra ID.', 'Huntress is required on every client — it is included in every proposal option.'] },
      { id: 'tickets', title: '16. Tickets, SLA & projects', bullets: ['Drag tickets between columns (New → In progress → Waiting on client → Resolved).', 'SLA timers: P1 4 hours, P2 8 hours, P3 24 hours, P4 72 hours.', 'Mark tickets billable and log hours — they appear in the invoice builder.', 'Clients can open tickets from their portal; you can also open them by command or sync them with Zammad or ITFlow.', 'Projects — milestones, progress and billable hours.'] },
      { id: 'docs', title: '17. Documentation & tools', bullets: ['SOPs & runbooks, Users & groups, and password rotation (executed through your RMM, UniFi or Microsoft Graph — Omni never stores passwords in the browser).', 'Tools — toolbox, print management (toner and errors), backup console and scripting.'] },
      { id: 'integrations', title: '18. Integrations', intro: 'Connect each tool once in Integrations. Your keys are encrypted and used only by your workspace.', bullets: ['RMM & patching: Tactical RMM, NinjaOne, Atera, Automox, Chocolatey.', 'Microsoft: Microsoft 365, Entra ID & Entra admin center, Windows Server / Active Directory.', 'Security: Huntress. Network: UniFi, Uptime Kuma, Lansweeper.', 'Remote access: RustDesk. Virtualization & backup: Proxmox VE, Proxmox Backup Server, Synology, Datto/Veeam.', 'Ticketing: Zammad, ITFlow. Communication: Webex, Fusion Connect, email, AI voice, calendar.', 'Finance: QuickBooks Online, Stripe, Gusto. AI: Claude.'], tip: 'Self-hosted tools (Tactical RMM, Proxmox, Synology, Zammad, ITFlow, Uptime Kuma, RustDesk) must be reachable from the internet over HTTPS with a trusted certificate — a free Cloudflare Tunnel is the easiest way.' },
      { id: 'ai', title: '19. AI assistant', bullets: ['Ask questions about your clients, draft emails, summarize tickets and write proposal narratives (Business plan and up).'] },
      { id: 'team', title: '20. Team & client logins', steps: ['Team & Client Logins → Invite.', 'Choose a role: Admin (everything), Technician (no finance), Finance (billing and payroll) or Client (their own company only, in your branded portal).', 'They receive an email link to set their password. Remove access any time.'] },
      { id: 'brand', title: '21. Your website, client portal & branding', bullets: ['Admin & Branding → Company & branding: name, logo, colors, address, phone, labor rates and policies.', 'Website & domain: your public website (lead form, booking, pricing, services map) and client portal live at your Omni address or, on Business and Enterprise, your own domain.', 'Everything your clients see — website, portal, proposals, RFS, invoices, emails and notices — carries your brand, not Omni’s.'] },
      { id: 'mobile', title: '22. Omni on your phone', bullets: ['Android: install “Omni TotalStack MSP” from Google Play.', 'iPhone / iPad: open your Omni address in Safari → Share → Add to Home Screen.', 'Windows / Mac: in Chrome or Edge, click the install icon in the address bar.'] },
      { id: 'billing', title: '23. Your Omni plan & billing', bullets: ['Plan & Billing shows your plan, usage and payment method. Upgrade or downgrade any time; changes are prorated.', 'Starter $29.99/mo (1 staff, 1 client, 25 devices) · Unlimited $99/mo · Business $249/mo · Enterprise $4,500 one-time (your own standalone copy on your own domain, disconnected from the Omni platform).', 'If a payment fails, everything stays online for a 7-day grace period. After that the workspace, website and client portal pause until you pay — your data is never deleted for non-payment.', 'Download all your data any time from Plan & Billing.'] },
      { id: 'faq', title: '24. Troubleshooting & support', bullets: ['An integration says “not connected” → re-open its card in Integrations and re-check the keys.', 'A command says “no matching agents” → make sure the computer name and client name match your RMM.', 'A self-hosted tool “did not answer in time” → it isn’t reachable from the internet; set up a Cloudflare Tunnel.', `Still stuck? Email ${o.supportEmail} with a screenshot and we’ll help.`] },
    ],
  }
}

/** Guide for an MSP's own clients: support tickets, invoices and paying. */
export function clientGuide(m: MspContact): Guide {
  const contact = [m.phone && `call ${m.phone}`, m.email && `email ${m.email}`].filter(Boolean).join(' or ')
  return {
    id: 'client',
    title: `${m.name} — Client Guide`,
    subtitle: 'How to get IT help, see your invoices and pay online',
    audience: `For the staff and owners of businesses supported by ${m.name}`,
    sections: [
      { id: 'portal', title: '1. Your client portal', intro: `${m.name} gives your business a secure online portal where you can request help, follow your requests, see your devices and projects, and view and pay invoices.`, bullets: [`Portal address: ${m.portalUrl}`, 'Bookmark it, or save it to your phone’s home screen.'] },
      { id: 'signin', title: '2. Signing in the first time', steps: [`Look for an email from ${m.name} titled “${m.name}: your client portal”.`, 'Click “Accept invitation” and choose a password (the link expires after 14 days — ask us for a new one if it has).', `From then on, sign in at ${m.portalUrl} with your email and password.`], tip: 'Forgot your password? Click “Forgot password” on the sign-in page.' },
      { id: 'ticket', title: '3. Submitting a support request (ticket)', steps: ['Sign in to the portal.', 'Click “New request” (on the Overview page or the Tickets tab).', 'In “What do you need help with?” write a short title, e.g. “Printer in the front office won’t print”.', 'In Details, add anything that helps: which computer or person, what you were doing, any error message, and when it started. You can paste a screenshot link.', 'Choose a priority (see below) and click Submit.', 'You’ll see your request with its number in the Tickets tab. We’ll update it as we work on it.'], tip: `Always include the computer name if you know it — it’s on a sticker on the computer, or in the “My devices” tab.` },
      { id: 'priority', title: '4. Choosing the right priority', bullets: ['P1 — Critical: the whole office can’t work (internet down, server down, suspected hack). We respond within 4 hours. Please ALSO call us.', 'P2 — High: one person can’t work, or an important system is failing. Within 8 hours.', 'P3 — Normal: something is broken but there’s a workaround. Within 24 hours.', 'P4 — Low: questions, new user setups planned ahead, small changes. Within 72 hours.'], tip: 'Think you clicked a bad link or see a ransom message? Unplug the computer’s network cable or turn off Wi-Fi, don’t turn the computer off, and call us immediately.' },
      { id: 'track', title: '5. Following your request', bullets: ['Tickets tab statuses: New (received), In progress (we’re working on it), Waiting (we need something from you), Resolved (done).', 'Reply to our emails or update the ticket if anything changes.', 'If a resolved problem comes back, open a new request and mention the old ticket number.'] },
      { id: 'other', title: '6. Other ways to reach us', bullets: [contact ? `You can also ${contact}.` : 'You can also contact us by phone or email.', m.hours ? `Support hours: ${m.hours}.` : 'Our support hours are listed on our website.', m.emergency ? `After-hours emergencies: ${m.emergency}.` : 'For after-hours emergencies, call and choose the emergency option.'] },
      { id: 'invoices', title: '7. Viewing your invoices', steps: ['Sign in and open the “Invoices & Payments” tab.', 'You’ll see every invoice with its due date, amount and status (Sent, Overdue or Paid).', 'Click the download icon to save or print the PDF.', 'Your current balance is shown on the Overview page.'] },
      { id: 'pay', title: '8. Paying online', steps: ['Open “Invoices & Payments” and click Pay next to the invoice (or “Pay now” on the Overview page).', 'Choose how to pay: Bank (ACH) — lowest fees, takes 3–5 business days; Credit / debit card — instant; Apple Pay / Google Pay — instant on supported phones and browsers.', 'Enter your details on the secure payment page and confirm.', 'You’ll see “Payment successful”. Your receipt is in “Payment history” — click Receipt to download it.'], tip: 'Payments are processed securely by Stripe. We never see or store your full card or bank numbers.' },
      { id: 'autopay', title: '9. Auto-pay (recommended)', bullets: ['Turn on auto-pay when you pay, and future invoices are paid automatically on their due date with your saved method.', 'You can change your saved payment method or turn auto-pay off any time — just ask us.'] },
      { id: 'late', title: '10. If a payment is late', bullets: [m.paymentTerms ? `Our payment terms: ${m.paymentTerms}.` : 'Invoices are due by the date shown on the invoice.', 'You’ll get a friendly reminder when an invoice is overdue.', 'If an invoice stays unpaid, a formal Notice of Non-Payment may be sent. Talk to us before that point — we’re happy to set up a payment plan.'] },
      { id: 'more', title: '11. What else is in the portal', bullets: ['My devices — your computers and equipment, whether each is protected by our 24/7 security monitoring (Huntress), and warranty dates.', 'Projects — progress and milestones for any project we’re doing for you.', 'Documents — your agreements, proposals and other files we share with you.', 'Security protection — the share of your devices monitored around the clock.'] },
      { id: 'tips', title: '12. Tips for faster help', bullets: ['One problem per request — it gets to the right technician faster.', 'Restarting the computer fixes many issues — try it once before submitting (unless you suspect a virus).', 'Never share your password with anyone — we will never ask for it by email or phone.', `${m.name}${m.address ? ` · ${m.address}` : ''}${m.phone ? ` · ${m.phone}` : ''}${m.email ? ` · ${m.email}` : ''}`] },
    ],
  }
}

/** Plain-text version (for copying into an email). */
export function guideText(g: Guide) {
  const out = [g.title, g.subtitle, g.audience, '']
  for (const s of g.sections) {
    out.push(s.title)
    if (s.intro) out.push(s.intro)
    s.steps?.forEach((x, i) => out.push(`  ${i + 1}. ${x}`))
    s.bullets?.forEach((x) => out.push(`  • ${x}`))
    if (s.tip) out.push(`  Tip: ${s.tip}`)
    out.push('')
  }
  return out.join('\n')
}
