// Integration registry. "Core" integrations have real server adapters in /api/*.
// Secrets are NEVER stored in the browser in production: the form posts them to /api/integrations/save,
// which writes them to Supabase (encrypted column) or you set them as Vercel environment variables.
import type { IntegrationId } from './types'

export interface Field { key: string; label: string; secret?: boolean; placeholder?: string; help?: string }
export interface IntegrationDef {
  id: IntegrationId
  name: string
  category: 'AI' | 'RMM' | 'Security' | 'Microsoft' | 'Network' | 'Inventory' | 'Finance' | 'Payroll' | 'Communication' | 'Backup' | 'Print'
  blurb: string
  powers: string[]
  fields: Field[]
  envVars: string[]
  docs: string
  howTo: string[]
}

export const INTEGRATIONS: IntegrationDef[] = [
  { id: 'claude', name: 'Claude (Anthropic)', category: 'AI', blurb: 'AI assistant for proposals, ticket triage, QBR summaries and client emails.', powers: ['AI Assistant', 'Proposal narratives', 'Ticket suggestions'], fields: [{ key: 'apiKey', label: 'Anthropic API key', secret: true, placeholder: 'sk-ant-…' }, { key: 'model', label: 'Model', placeholder: 'claude-sonnet-4-5' }], envVars: ['ANTHROPIC_API_KEY', 'ANTHROPIC_MODEL'], docs: 'https://docs.claude.com', howTo: ['Go to console.anthropic.com → API Keys', 'Create a key named "Omni TotalStack"', 'Paste it here'] },
  { id: 'rmm', name: 'RMM (NinjaOne / Atera / Datto / ConnectWise)', category: 'RMM', blurb: 'Device inventory, health, alerts, scripting and patch deployment.', powers: ['Infrastructure', 'Patching', 'Remote access', 'Alerts'], fields: [{ key: 'vendor', label: 'Vendor', placeholder: 'ninjaone | atera | datto | connectwise' }, { key: 'baseUrl', label: 'API base URL', placeholder: 'https://app.ninjarmm.com' }, { key: 'clientId', label: 'Client ID' }, { key: 'clientSecret', label: 'Client secret / API key', secret: true }], envVars: ['RMM_VENDOR', 'RMM_BASE_URL', 'RMM_CLIENT_ID', 'RMM_CLIENT_SECRET'], docs: 'https://app.ninjarmm.com/apidocs/', howTo: ['In your RMM admin, open API / Integrations', 'Create an API client with "Monitoring" and "Management" scopes', 'Copy the client ID and secret here'] },
  { id: 'huntress', name: 'Huntress', category: 'Security', blurb: 'Managed EDR, ITDR, SAT and SIEM — agents, incidents and organizations. Required on every client.', powers: ['Security panel', 'Agent coverage', 'Incident alerts', 'Proposal pricing'], fields: [{ key: 'apiKey', label: 'API key', secret: true }, { key: 'apiSecret', label: 'API secret', secret: true }, { key: 'portalUrl', label: 'Partner portal URL', placeholder: 'https://yourmsp.huntress.io' }], envVars: ['HUNTRESS_API_KEY', 'HUNTRESS_API_SECRET'], docs: 'https://api.huntress.io/docs', howTo: ['Huntress portal → Settings → API Credentials', 'Generate a key pair', 'Paste both values here'] },
  { id: 'm365', name: 'Microsoft 365 (Graph)', category: 'Microsoft', blurb: 'Licenses, mailboxes, Teams, SharePoint, secure score and service health per tenant (GDAP).', powers: ['Client users', 'License costs', 'Secure Score', 'Service health'], fields: [{ key: 'tenantId', label: 'Partner tenant ID' }, { key: 'clientId', label: 'App (client) ID' }, { key: 'clientSecret', label: 'Client secret', secret: true }], envVars: ['MS_TENANT_ID', 'MS_CLIENT_ID', 'MS_CLIENT_SECRET'], docs: 'https://learn.microsoft.com/graph/overview', howTo: ['Entra admin center → App registrations → New', 'Add Graph application permissions: User.Read.All, Directory.Read.All, Reports.Read.All, ServiceHealth.Read.All', 'Grant admin consent, create a client secret', 'Use GDAP relationships to reach client tenants'] },
  { id: 'entra', name: 'Microsoft Entra ID (formerly Azure AD)', category: 'Microsoft', blurb: 'Users, groups, MFA status, sign-ins, conditional access and stale accounts.', powers: ['Network documentation', 'MFA gaps', 'Stale account alerts'], fields: [{ key: 'useM365', label: 'Use the Microsoft 365 app registration? (yes/no)', placeholder: 'yes' }], envVars: ['MS_TENANT_ID', 'MS_CLIENT_ID', 'MS_CLIENT_SECRET'], docs: 'https://learn.microsoft.com/entra/', howTo: ['Uses the same app registration as Microsoft 365', 'Add UserAuthenticationMethod.Read.All and AuditLog.Read.All permissions'] },
  { id: 'unifi', name: 'UniFi Site Manager', category: 'Network', blurb: 'Gateways, switches, APs, site health, WAN status and outage detection.', powers: ['Site status', 'Outage alerts', 'Topology', 'Firmware'], fields: [{ key: 'apiKey', label: 'Site Manager API key', secret: true }], envVars: ['UNIFI_API_KEY'], docs: 'https://developer.ui.com/site-manager-api/', howTo: ['unifi.ui.com → API', 'Create an API key', 'Paste it here — all your sites appear automatically'] },
  { id: 'inventory', name: 'Inventory / Procurement (Pax8, Ingram, D&H, Sortly)', category: 'Inventory', blurb: 'Stock, distributor pricing, orders and license provisioning.', powers: ['Inventory', 'Procurement', 'Quote builder'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'pax8 | ingram | sortly' }, { key: 'apiKey', label: 'API key', secret: true }], envVars: ['INVENTORY_PROVIDER', 'INVENTORY_API_KEY'], docs: 'https://devx.pax8.com', howTo: ['Request API access from your distributor portal', 'Paste the key here'] },
  { id: 'quickbooks', name: 'QuickBooks Online', category: 'Finance', blurb: 'Revenue, expenses, P&L, aging A/R, vendor bills and tax categories. Invoices & payments sync both ways.', powers: ['Finance dashboard', 'Invoice sync', 'Vendor bills'], fields: [{ key: 'clientId', label: 'Intuit app client ID' }, { key: 'clientSecret', label: 'Client secret', secret: true }, { key: 'realmId', label: 'Company (realm) ID' }], envVars: ['QBO_CLIENT_ID', 'QBO_CLIENT_SECRET', 'QBO_REDIRECT_URI'], docs: 'https://developer.intuit.com', howTo: ['developer.intuit.com → Create an app (Accounting scope)', 'Set redirect URI to https://YOUR-DOMAIN/api/quickbooks/callback', 'Click "Connect to QuickBooks" after saving'] },
  { id: 'stripe', name: 'Stripe Payments', category: 'Finance', blurb: 'ACH, cards, Apple Pay / Google Pay, saved methods, auto-pay and receipts.', powers: ['Client payments', 'Auto-pay', 'Receipts'], fields: [{ key: 'publishableKey', label: 'Publishable key', placeholder: 'pk_live_…' }, { key: 'secretKey', label: 'Secret key', secret: true }, { key: 'webhookSecret', label: 'Webhook signing secret', secret: true }], envVars: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET', 'VITE_STRIPE_PUBLISHABLE_KEY'], docs: 'https://docs.stripe.com', howTo: ['dashboard.stripe.com → Developers → API keys', 'Enable ACH Direct Debit, Apple Pay and Google Pay in Payment methods', 'Add a webhook to https://YOUR-DOMAIN/api/stripe/webhook'] },
  { id: 'gusto', name: 'Payroll (Gusto / QuickBooks Payroll)', category: 'Payroll', blurb: 'Pay periods, employees & contractors, hours, PTO, direct deposit and compliance.', powers: ['Payroll console', 'Compliance alerts'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'gusto | qbo-payroll' }, { key: 'token', label: 'API token', secret: true }], envVars: ['PAYROLL_PROVIDER', 'PAYROLL_TOKEN'], docs: 'https://docs.gusto.com', howTo: ['Create a Gusto developer app', 'Authorize your company', 'Paste the token'] },
  { id: 'voice', name: 'AI Voice Calls (Vapi / Retell / ElevenLabs)', category: 'Communication', blurb: 'Outbound AI calls to new website leads that qualify them and book appointments.', powers: ['Landing page "Call me now"', 'Lead qualification'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'vapi | retell | elevenlabs' }, { key: 'apiKey', label: 'API key', secret: true }, { key: 'assistantId', label: 'Assistant / agent ID' }, { key: 'phoneNumberId', label: 'Caller phone number ID' }], envVars: ['VOICE_PROVIDER', 'VOICE_API_KEY', 'VOICE_ASSISTANT_ID', 'VOICE_PHONE_NUMBER_ID'], docs: 'https://docs.vapi.ai', howTo: ['Create an assistant with the script in docs/AI_VOICE_SCRIPT.md', 'Buy or import a phone number', 'Paste the IDs here'] },
  { id: 'resend', name: 'Email (Resend / SMTP)', category: 'Communication', blurb: 'Sends weekly update emails, invoices, receipts and notices.', powers: ['Weekly client update email', 'Invoice email'], fields: [{ key: 'apiKey', label: 'Resend API key', secret: true }, { key: 'from', label: 'From address', placeholder: 'updates@yourmsp.com' }], envVars: ['SMTP_USER', 'SMTP_PASS', 'RESEND_API_KEY', 'EMAIL_FROM_ADDRESS'], docs: 'https://resend.com/docs', howTo: ['Easiest: a Gmail account → Google Account → Security → 2-Step Verification on → App passwords → create one; set SMTP_USER (the Gmail address) and SMTP_PASS (the 16-letter app password)', 'Or: resend.com → Domains → verify your domain → create an API key'] },
  { id: 'calendar', name: 'Calendar (Microsoft Bookings / Google / Cal.com)', category: 'Communication', blurb: 'Appointment booking from the landing page and AI calls.', powers: ['Book appointments'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'cal.com | google | bookings' }, { key: 'apiKey', label: 'API key / link', secret: true }], envVars: ['CALENDAR_PROVIDER', 'CALENDAR_API_KEY'], docs: 'https://cal.com/docs', howTo: ['Create an event type "IT Consultation (30 min)"', 'Paste the API key'] },
  { id: 'backup', name: 'Backup (Datto / Veeam / Acronis / Axcient)', category: 'Backup', blurb: 'Backup job status and restore testing evidence.', powers: ['Backup status', 'QBR evidence'], fields: [{ key: 'vendor', label: 'Vendor' }, { key: 'apiKey', label: 'API key', secret: true }], envVars: ['BACKUP_VENDOR', 'BACKUP_API_KEY'], docs: '', howTo: ['Create an API key in your backup console'] },
  { id: 'print', name: 'Print fleet (HP / Canon / Brother / PaperCut)', category: 'Print', blurb: 'Printer status, toner levels and error logs (SNMP via Omni Agent or vendor cloud).', powers: ['Print services panel', 'Toner auto-order'], fields: [{ key: 'mode', label: 'Mode', placeholder: 'snmp-agent | papercut' }, { key: 'apiKey', label: 'API key (if cloud)', secret: true }], envVars: ['PRINT_MODE', 'PRINT_API_KEY'], docs: '', howTo: ['Enable SNMP v2c/v3 on printers', 'The Omni Agent reports toner automatically'] },
]

/** The wider marketplace (adapter slots). Core ones above are fully wired; these are catalogued for the roadmap. */
export const MARKETPLACE: Record<string, string[]> = {
  'AI': ['Claude', 'Microsoft Copilot', 'OpenAI', 'Google Gemini'],
  'RMM': ['NinjaOne', 'Atera', 'Datto RMM', 'ConnectWise Automate', 'Kaseya VSA', 'N-able N-sight', 'Syncro', 'Tactical RMM', 'Level', 'Action1'],
  'PSA & Ticketing': ['HaloPSA', 'ConnectWise Manage', 'Autotask', 'Syncro PSA', 'Zendesk', 'Freshdesk', 'Jira Service Management'],
  'Security': ['Huntress', 'SentinelOne', 'CrowdStrike', 'Microsoft Defender', 'Sophos', 'Bitdefender', 'Blackpoint', 'Todyl', 'Proofpoint', 'Mimecast', 'Avanan', 'IronScales', 'DNSFilter', 'Cisco Umbrella', 'KnowBe4', 'Keeper', 'Bitwarden', 'Dark Web ID', 'Liongard', 'RocketCyber'],
  'Microsoft & Identity': ['Microsoft 365', 'Entra ID', 'Intune', 'Azure', 'Active Directory (on-prem)', 'Google Workspace', 'Okta', 'Duo'],
  'Networking': ['UniFi', 'Meraki', 'Fortinet', 'SonicWall', 'WatchGuard', 'Aruba', 'Auvik', 'Domotz', 'Lansweeper', 'Fing', 'SNMP', 'Omada', 'Starlink'],
  'Backup': ['Datto BCDR', 'Veeam', 'Acronis', 'Axcient', 'Cove', 'Backupify', 'Dropsuite'],
  'Finance & Payments': ['QuickBooks Online', 'Xero', 'Stripe', 'Square', 'PayPal', 'GoCardless', 'Bill.com', 'Expensify'],
  'Payroll & HR': ['Gusto', 'QuickBooks Payroll', 'ADP', 'Paychex', 'Rippling', 'Deel'],
  'Distribution & Procurement': ['Pax8', 'Ingram Micro', 'TD SYNNEX', 'D&H', 'Amazon Business', 'CDW', 'Dell Premier', 'Sortly'],
  'CRM & Sales': ['HubSpot', 'Salesforce', 'Zoho CRM', 'Pipedrive', 'PandaDoc', 'DocuSign'],
  'Communication': ['Slack', 'Microsoft Teams', 'Zoom', 'Twilio', 'Vapi', 'Retell AI', 'ElevenLabs', 'Resend', 'RingCentral', '3CX'],
  'Projects & Docs': ['ClickUp', 'Monday.com', 'Asana', 'Notion', 'IT Glue', 'Hudu', 'Google Drive', 'OneDrive', 'Dropbox', 'SharePoint'],
  'Print': ['HP', 'Canon', 'Brother', 'Epson', 'Xerox', 'PaperCut'],
}
export const MARKETPLACE_COUNT = Object.values(MARKETPLACE).reduce((a, l) => a + l.length, 0)
