// Integration registry. "Core" integrations have real server adapters in /api/*.
// Secrets are NEVER stored in the browser in production: the form posts them to /api/integrations/save,
// which writes them to Supabase (encrypted column) or you set them as Vercel environment variables.
import type { IntegrationId } from './types'

export interface Field { key: string; label: string; secret?: boolean; placeholder?: string; help?: string }
export interface IntegrationDef {
  id: IntegrationId
  name: string
  category: 'AI' | 'RMM' | 'Security' | 'Microsoft' | 'Network' | 'Inventory' | 'Finance' | 'Payroll' | 'Communication' | 'Backup' | 'Print'
    | 'Patching' | 'Remote Access' | 'Virtualization' | 'Monitoring' | 'PSA & Ticketing' | 'Servers' | 'Voice & Connectivity'
  blurb: string
  /** Commands you can type in the Command Console for this integration (examples). */
  commands?: string[]
  /** Runs on the MSP's own server — must be reachable from the internet over HTTPS (e.g. Cloudflare Tunnel). */
  selfHosted?: boolean
  /** Vendor admin portal, opened from the card. */
  portal?: string
  powers: string[]
  fields: Field[]
  envVars: string[]
  docs: string
  howTo: string[]
}

export const INTEGRATIONS: IntegrationDef[] = [
  { id: 'claude', name: 'Claude (Anthropic)', category: 'AI', blurb: 'AI assistant for proposals, ticket triage, QBR summaries and client emails.', powers: ['AI Assistant', 'Proposal narratives', 'Ticket suggestions'], fields: [{ key: 'apiKey', label: 'Anthropic API key', secret: true, placeholder: 'sk-ant-…' }, { key: 'model', label: 'Model', placeholder: 'claude-sonnet-4-5' }], envVars: ['ANTHROPIC_API_KEY', 'ANTHROPIC_MODEL'], docs: 'https://docs.claude.com', howTo: ['Go to console.anthropic.com → API Keys', 'Create a key named "Omni TotalStack"', 'Paste it here'] },
  { id: 'rmm', name: 'RMM (NinjaOne / Atera / Datto / ConnectWise)', category: 'RMM', blurb: 'Device inventory, health, alerts, scripting and patch deployment.', powers: ['Infrastructure', 'Patching', 'Remote access', 'Alerts'], fields: [{ key: 'vendor', label: 'Vendor', placeholder: 'ninjaone | atera | datto | connectwise' }, { key: 'baseUrl', label: 'API base URL', placeholder: 'https://app.ninjarmm.com' }, { key: 'clientId', label: 'Client ID' }, { key: 'clientSecret', label: 'Client secret / API key', secret: true }], envVars: ['RMM_VENDOR', 'RMM_BASE_URL', 'RMM_CLIENT_ID', 'RMM_CLIENT_SECRET'], docs: 'https://app.ninjarmm.com/apidocs/', howTo: ['In your RMM admin, open API / Integrations', 'Create an API client with "Monitoring" and "Management" scopes', 'Copy the client ID and secret here'] },
  { id: 'huntress', name: 'Huntress', category: 'Security', blurb: 'Managed EDR, ITDR, SAT and SIEM — agents, incidents and organizations. Required on every client.', powers: ['Security panel', 'Agent coverage', 'Incident alerts', 'Proposal pricing'], fields: [{ key: 'apiKey', label: 'API key', secret: true }, { key: 'apiSecret', label: 'API secret', secret: true }, { key: 'portalUrl', label: 'Partner portal URL', placeholder: 'https://yourmsp.huntress.io' }], envVars: ['HUNTRESS_API_KEY', 'HUNTRESS_API_SECRET'], docs: 'https://api.huntress.io/docs', howTo: ['Huntress portal → Settings → API Credentials', 'Generate a key pair', 'Paste both values here'] },
  { id: 'm365', name: 'Microsoft 365 (Graph)', category: 'Microsoft', blurb: 'Licenses, mailboxes, Teams, SharePoint, secure score and service health per tenant (GDAP).', powers: ['Client users', 'License costs', 'Secure Score', 'Service health'], fields: [{ key: 'tenantId', label: 'Partner tenant ID' }, { key: 'clientId', label: 'App (client) ID' }, { key: 'clientSecret', label: 'Client secret', secret: true }], envVars: ['MS_TENANT_ID', 'MS_CLIENT_ID', 'MS_CLIENT_SECRET'], docs: 'https://learn.microsoft.com/graph/overview', howTo: ['Entra admin center → App registrations → New', 'Add Graph application permissions: User.Read.All, Directory.Read.All, Reports.Read.All, ServiceHealth.Read.All', 'Grant admin consent, create a client secret', 'Use GDAP relationships to reach client tenants'] },
  { id: 'entra', name: 'Microsoft Entra ID & Entra admin center', category: 'Microsoft', blurb: 'Users, groups, MFA status, sign-ins, conditional access and stale accounts — plus add, disable, enable, delete users and reset passwords from the Command Console.', powers: ['Network documentation', 'MFA gaps', 'Stale account alerts', 'User admin commands'], commands: ['add user Jane Doe jane@client.com', 'disable user john@client.com', 'reset password john@client.com', 'sign out user john@client.com everywhere'], portal: 'https://entra.microsoft.com', fields: [{ key: 'useM365', label: 'Use the Microsoft 365 app registration? (yes/no)', placeholder: 'yes' }], envVars: ['MS_TENANT_ID', 'MS_CLIENT_ID', 'MS_CLIENT_SECRET'], docs: 'https://learn.microsoft.com/entra/', howTo: ['Uses the same app registration as Microsoft 365 (entra.microsoft.com → App registrations)', 'Add Graph application permissions: User.ReadWrite.All, UserAuthenticationMethod.Read.All, AuditLog.Read.All (and Directory.AccessAsUser.All is NOT needed)', 'For password resets also assign the app the "User Administrator" role', 'Grant admin consent — client tenants are reached through your GDAP relationships'] },
  { id: 'unifi', name: 'UniFi Site Manager', category: 'Network', blurb: 'Gateways, switches, APs, site health, WAN status and outage detection.', powers: ['Site status', 'Outage alerts', 'Topology', 'Firmware'], fields: [{ key: 'apiKey', label: 'Site Manager API key', secret: true }], envVars: ['UNIFI_API_KEY'], docs: 'https://developer.ui.com/site-manager-api/', howTo: ['unifi.ui.com → API', 'Create an API key', 'Paste it here — all your sites appear automatically'] },
  { id: 'inventory', name: 'Inventory / Procurement (Pax8, Ingram, D&H, Sortly)', category: 'Inventory', blurb: 'Stock, distributor pricing, orders and license provisioning.', powers: ['Inventory', 'Procurement', 'Quote builder'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'pax8 | ingram | sortly' }, { key: 'apiKey', label: 'API key', secret: true }], envVars: ['INVENTORY_PROVIDER', 'INVENTORY_API_KEY'], docs: 'https://devx.pax8.com', howTo: ['Request API access from your distributor portal', 'Paste the key here'] },
  { id: 'quickbooks', name: 'QuickBooks Online', category: 'Finance', blurb: 'Revenue, expenses, P&L, aging A/R, vendor bills and tax categories. Invoices & payments sync both ways.', powers: ['Finance dashboard', 'Invoice sync', 'Vendor bills'], fields: [{ key: 'clientId', label: 'Intuit app client ID' }, { key: 'clientSecret', label: 'Client secret', secret: true }, { key: 'realmId', label: 'Company (realm) ID' }], envVars: ['QBO_CLIENT_ID', 'QBO_CLIENT_SECRET', 'QBO_REDIRECT_URI'], docs: 'https://developer.intuit.com', howTo: ['developer.intuit.com → Create an app (Accounting scope)', 'Set redirect URI to https://YOUR-DOMAIN/api/quickbooks/callback', 'Click "Connect to QuickBooks" after saving'] },
  { id: 'stripe', name: 'Stripe Payments', category: 'Finance', blurb: 'ACH, cards, Apple Pay / Google Pay, saved methods, auto-pay and receipts.', powers: ['Client payments', 'Auto-pay', 'Receipts'], fields: [{ key: 'publishableKey', label: 'Publishable key', placeholder: 'pk_live_…' }, { key: 'secretKey', label: 'Secret key', secret: true }, { key: 'webhookSecret', label: 'Webhook signing secret', secret: true }], envVars: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET', 'VITE_STRIPE_PUBLISHABLE_KEY'], docs: 'https://docs.stripe.com', howTo: ['dashboard.stripe.com → Developers → API keys', 'Enable ACH Direct Debit, Apple Pay and Google Pay in Payment methods', 'Add a webhook to https://YOUR-DOMAIN/api/stripe/webhook'] },
  { id: 'gusto', name: 'Payroll (Gusto / QuickBooks Payroll)', category: 'Payroll', blurb: 'Pay periods, employees & contractors, hours, PTO, direct deposit and compliance.', powers: ['Payroll console', 'Compliance alerts'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'gusto | qbo-payroll' }, { key: 'token', label: 'API token', secret: true }], envVars: ['PAYROLL_PROVIDER', 'PAYROLL_TOKEN'], docs: 'https://docs.gusto.com', howTo: ['Create a Gusto developer app', 'Authorize your company', 'Paste the token'] },
  { id: 'voice', name: 'AI Voice Calls (Vapi / Retell / ElevenLabs)', category: 'Communication', blurb: 'Outbound AI calls to new website leads that qualify them and book appointments.', powers: ['Landing page "Call me now"', 'Lead qualification'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'vapi | retell | elevenlabs' }, { key: 'apiKey', label: 'API key', secret: true }, { key: 'assistantId', label: 'Assistant / agent ID' }, { key: 'phoneNumberId', label: 'Caller phone number ID' }], envVars: ['VOICE_PROVIDER', 'VOICE_API_KEY', 'VOICE_ASSISTANT_ID', 'VOICE_PHONE_NUMBER_ID'], docs: 'https://docs.vapi.ai', howTo: ['Create an assistant with the script in docs/AI_VOICE_SCRIPT.md', 'Buy or import a phone number', 'Paste the IDs here'] },
  { id: 'resend', name: 'Email (Resend / SMTP)', category: 'Communication', blurb: 'Sends weekly update emails, invoices, receipts and notices.', powers: ['Weekly client update email', 'Invoice email'], fields: [{ key: 'apiKey', label: 'Resend API key', secret: true }, { key: 'from', label: 'From address', placeholder: 'updates@yourmsp.com' }], envVars: ['SMTP_USER', 'SMTP_PASS', 'RESEND_API_KEY', 'EMAIL_FROM_ADDRESS'], docs: 'https://resend.com/docs', howTo: ['Easiest: a Gmail account → Google Account → Security → 2-Step Verification on → App passwords → create one; set SMTP_USER (the Gmail address) and SMTP_PASS (the 16-letter app password)', 'Or: resend.com → Domains → verify your domain → create an API key'] },
  { id: 'calendar', name: 'Calendar (Microsoft Bookings / Google / Cal.com)', category: 'Communication', blurb: 'Appointment booking from the landing page and AI calls.', powers: ['Book appointments'], fields: [{ key: 'provider', label: 'Provider', placeholder: 'cal.com | google | bookings' }, { key: 'apiKey', label: 'API key / link', secret: true }], envVars: ['CALENDAR_PROVIDER', 'CALENDAR_API_KEY'], docs: 'https://cal.com/docs', howTo: ['Create an event type "IT Consultation (30 min)"', 'Paste the API key'] },
  { id: 'backup', name: 'Backup (Datto / Veeam / Acronis / Axcient)', category: 'Backup', blurb: 'Backup job status and restore testing evidence.', powers: ['Backup status', 'QBR evidence'], fields: [{ key: 'vendor', label: 'Vendor' }, { key: 'apiKey', label: 'API key', secret: true }], envVars: ['BACKUP_VENDOR', 'BACKUP_API_KEY'], docs: '', howTo: ['Create an API key in your backup console'] },
  { id: 'print', name: 'Print fleet (HP / Canon / Brother / PaperCut)', category: 'Print', blurb: 'Printer status, toner levels and error logs (SNMP via Omni Agent or vendor cloud).', powers: ['Print services panel', 'Toner auto-order'], fields: [{ key: 'mode', label: 'Mode', placeholder: 'snmp-agent | papercut' }, { key: 'apiKey', label: 'API key (if cloud)', secret: true }], envVars: ['PRINT_MODE', 'PRINT_API_KEY'], docs: '', howTo: ['Enable SNMP v2c/v3 on printers', 'The Omni Agent reports toner automatically'] },
  { id: 'tacticalrmm', name: 'Tactical RMM', category: 'RMM', selfHosted: true, blurb: 'Open-source RMM: agents, checks, alerts, remote shell, Windows Update and Chocolatey software installs. The main engine Omni uses to run commands on devices.', powers: ['Run commands', 'Windows updates', 'Reboots', 'Software installs', 'Device list'], commands: ['update windows 11 on all devices', 'reboot FRONTDESK-01', 'run "ipconfig /flushdns" on all devices at Acme', 'install chrome on all devices at Acme'], fields: [{ key: 'baseUrl', label: 'API URL', placeholder: 'https://api.rmm.yourmsp.com' }, { key: 'apiKey', label: 'API key', secret: true }], envVars: [], docs: 'https://docs.tacticalrmm.com/functions/api/', howTo: ['Tactical RMM → Settings → Global Settings → API Keys → Add key', 'Use your API domain (the "api." address you set at install), e.g. https://api.rmm.yourmsp.com', 'It must be reachable from the internet over HTTPS'] },
  { id: 'automox', name: 'Automox', category: 'Patching', blurb: 'Cloud patching for Windows, macOS and Linux: devices, policies, patch status and on-demand patch/reboot.', powers: ['Patching', 'Policy runs', 'Reboots', 'Device inventory'], commands: ['update windows 11 at Acme', 'reboot all devices at Acme', 'patch status'], portal: 'https://console.automox.com', fields: [{ key: 'orgId', label: 'Organization ID', placeholder: '12345' }, { key: 'apiKey', label: 'API key', secret: true }], envVars: [], docs: 'https://developer.automox.com', howTo: ['console.automox.com → Settings → Secrets & Keys → Add API key', 'Your Organization ID is in the console URL (?o=12345)', 'Paste both here'] },
  { id: 'chocolatey', name: 'Chocolatey', category: 'Patching', blurb: 'Windows software install, upgrade and removal (choco). Commands run through Tactical RMM on the devices you pick.', powers: ['Install software', 'Upgrade all software', 'Uninstall software'], commands: ['install chrome on all devices at Acme', 'upgrade all software on FRONTDESK-01', 'uninstall zoom on RECEPTION-02'], fields: [{ key: 'source', label: 'Package source (optional)', placeholder: 'https://community.chocolatey.org/api/v2/ or your internal repo' }], envVars: [], docs: 'https://docs.chocolatey.org/en-us/choco/commands/', howTo: ['Connect Tactical RMM first — it runs the choco commands on your devices', 'Chocolatey is installed automatically on Tactical RMM agents', 'Optional: enter your internal package repository URL'] },
  { id: 'winserver', name: 'Windows Server (Active Directory, DNS, DHCP, Hyper-V)', category: 'Servers', blurb: 'On-premises Active Directory users, services and server health. Commands run as PowerShell on your domain controller through Tactical RMM.', powers: ['AD users', 'Restart services', 'Server health', 'Group Policy update'], commands: ['add user Jane Doe jane@acme.local in active directory', 'disable user jdoe in active directory', 'unlock user jdoe in active directory', 'restart service spooler on ACME-DC01'], fields: [{ key: 'domainControllers', label: 'Domain controller hostnames', placeholder: 'ACME-DC01, BAKER-DC01' }, { key: 'defaultOU', label: 'OU for new users (optional)', placeholder: 'OU=Staff,DC=acme,DC=local' }], envVars: [], docs: 'https://learn.microsoft.com/powershell/module/activedirectory/', howTo: ['Connect Tactical RMM and install its agent on each domain controller', 'List the domain controller hostnames here (one per client)', 'Omni runs the ActiveDirectory PowerShell module on the DC that matches the client'] },
  { id: 'rustdesk', name: 'RustDesk', category: 'Remote Access', selfHosted: true, blurb: 'Open-source remote desktop. Open a remote session to any device in one click or by typing "connect to FRONTDESK-01".', powers: ['Remote control', 'Device ID lookup'], commands: ['connect to FRONTDESK-01'], fields: [{ key: 'server', label: 'ID/relay server', placeholder: 'rustdesk.yourmsp.com' }, { key: 'apiUrl', label: 'RustDesk Server Pro API URL (optional)', placeholder: 'https://rustdesk.yourmsp.com' }, { key: 'apiToken', label: 'API token (Pro only)', secret: true }, { key: 'key', label: 'Public key (optional)' }], envVars: [], docs: 'https://rustdesk.com/docs/', howTo: ['Self-host hbbs/hbbr (or RustDesk Server Pro) and note your server address and public key', 'Pro: Web console → Settings → Tokens → create a token for device lookup', 'Put each device\'s RustDesk ID in its device record (Sites & Infrastructure) if you are not on Pro'] },
  { id: 'proxmox', name: 'Proxmox VE', category: 'Virtualization', selfHosted: true, blurb: 'Hypervisor nodes, VMs and containers: status, start, stop, reboot and snapshots.', powers: ['VM status', 'Start / stop / reboot', 'Snapshots'], commands: ['restart vm 101', 'snapshot vm 101', 'list vms'], fields: [{ key: 'baseUrl', label: 'API URL', placeholder: 'https://pve.yourmsp.com:8006' }, { key: 'tokenId', label: 'API token ID', placeholder: 'omni@pve!omni' }, { key: 'secret', label: 'API token secret', secret: true }], envVars: [], docs: 'https://pve.proxmox.com/wiki/Proxmox_VE_API', howTo: ['Datacenter → Permissions → API Tokens → Add (user omni@pve, token "omni")', 'Give it the PVEVMAdmin role on / (or only the pools you manage)', 'Use a trusted HTTPS certificate (e.g. Cloudflare Tunnel) — self-signed certificates are refused'] },
  { id: 'pbs', name: 'Proxmox Backup Server', category: 'Backup', selfHosted: true, blurb: 'Datastores, backup jobs, verification and garbage-collection status — shown on QBRs as backup evidence.', powers: ['Backup status', 'Datastore usage', 'QBR evidence'], commands: ['backup status', 'show failed backups'], fields: [{ key: 'baseUrl', label: 'API URL', placeholder: 'https://pbs.yourmsp.com:8007' }, { key: 'tokenId', label: 'API token ID', placeholder: 'omni@pbs!omni' }, { key: 'secret', label: 'API token secret', secret: true }], envVars: [], docs: 'https://pbs.proxmox.com/docs/api-viewer/', howTo: ['Configuration → Access Control → API Token → Add', 'Grant the token DatastoreAudit (read) on /datastore', 'Use a trusted HTTPS certificate'] },
  { id: 'synology', name: 'Synology NAS (DSM)', category: 'Backup', selfHosted: true, blurb: 'NAS health, volumes, disks and Hyper Backup / Active Backup task status.', powers: ['NAS health', 'Storage alerts', 'Backup status'], commands: ['nas status', 'backup status'], fields: [{ key: 'baseUrl', label: 'DSM URL', placeholder: 'https://nas.client.com:5001' }, { key: 'username', label: 'Service account username', placeholder: 'omni-monitor' }, { key: 'password', label: 'Password', secret: true }], envVars: [], docs: 'https://global.synologydownload.com/download/Document/Software/DeveloperGuide/Os/DSM/All/enu/DSM_Login_Web_API_Guide_enu.pdf', howTo: ['Control Panel → User → create "omni-monitor" (no 2-step verification on this account)', 'Give it read access only', 'Publish DSM over HTTPS with QuickConnect or a reverse proxy'] },
  { id: 'uptimekuma', name: 'Uptime Kuma', category: 'Monitoring', selfHosted: true, blurb: 'Website, service and ping monitors — any monitor that goes down shows on the site outage board.', powers: ['Outage board', 'Monitor status'], commands: ['monitor status', 'what is down'], fields: [{ key: 'baseUrl', label: 'Uptime Kuma URL', placeholder: 'https://status.yourmsp.com' }, { key: 'statusPages', label: 'Status page slugs', placeholder: 'acme, baker-law' }], envVars: [], docs: 'https://github.com/louislam/uptime-kuma/wiki', howTo: ['In Uptime Kuma create a Status Page for each client and add their monitors', 'Type the status page slugs here (the part after /status/)', 'Omni reads the public status page API — no password needed'] },
  { id: 'lansweeper', name: 'Lansweeper', category: 'Inventory', blurb: 'IT asset discovery and inventory: hardware, software, warranty and users across every site.', powers: ['Asset inventory', 'Warranty dates', 'Software audit'], commands: ['find device FRONTDESK-01', 'list assets at Acme'], portal: 'https://app.lansweeper.com', fields: [{ key: 'siteId', label: 'Site ID' }, { key: 'token', label: 'Personal access token', secret: true }], envVars: [], docs: 'https://developer.lansweeper.com', howTo: ['app.lansweeper.com → Settings → Developer tools → Personal access tokens', 'Copy your Site ID from the same page', 'Paste both here'] },
  { id: 'zammad', name: 'Zammad', category: 'PSA & Ticketing', selfHosted: true, blurb: 'Help desk tickets two-way: tickets you open in Omni or by command appear in Zammad, and Zammad tickets show in Tickets & SLA.', powers: ['Ticket sync', 'Create tickets'], commands: ['open ticket for Acme: printer offline'], fields: [{ key: 'baseUrl', label: 'Zammad URL', placeholder: 'https://helpdesk.yourmsp.com' }, { key: 'token', label: 'Access token', secret: true }, { key: 'group', label: 'Default group', placeholder: 'Users' }], envVars: [], docs: 'https://docs.zammad.org/en/latest/api/intro.html', howTo: ['Zammad → your avatar → Profile → Token Access → Create (ticket.agent permission)', 'Paste the token and your Zammad address'] },
  { id: 'itflow', name: 'ITFlow', category: 'PSA & Ticketing', selfHosted: true, blurb: 'Open-source PSA/documentation: clients, assets and tickets synced with Omni.', powers: ['Ticket sync', 'Client & asset sync'], commands: ['open ticket for Acme in itflow: new laptop setup'], fields: [{ key: 'baseUrl', label: 'ITFlow URL', placeholder: 'https://itflow.yourmsp.com' }, { key: 'apiKey', label: 'API key', secret: true }], envVars: [], docs: 'https://docs.itflow.org/api', howTo: ['ITFlow → Admin → API Keys → Create (all clients)', 'Paste the key and your ITFlow address'] },
  { id: 'webex', name: 'Webex', category: 'Communication', blurb: 'Webex users, licenses, meetings and calling — add or remove Webex users by command.', powers: ['User admin', 'Licenses', 'Meetings'], commands: ['add user Jane Doe jane@client.com in webex', 'delete user john@client.com in webex', 'list webex users'], portal: 'https://admin.webex.com', fields: [{ key: 'token', label: 'Access token (service app or integration)', secret: true }, { key: 'orgId', label: 'Organization ID (optional, for partner admins)' }], envVars: [], docs: 'https://developer.webex.com/docs/api/getting-started', howTo: ['developer.webex.com → My Webex Apps → Create a Service App', 'Scopes: spark-admin:people_read, spark-admin:people_write, spark-admin:licenses_read', 'Have a full admin authorize it in Control Hub, then paste the access token'] },
  { id: 'fusion', name: 'Fusion Connect', category: 'Voice & Connectivity', blurb: 'Business voice, internet circuits and SD-WAN from Fusion Connect: circuit list, account numbers and one-command support tickets emailed to Fusion.', powers: ['Circuit records', 'Carrier tickets'], commands: ['open fusion ticket for Acme: internet down'], portal: 'https://www.fusionconnect.com/customer-support', fields: [{ key: 'accountNumber', label: 'Fusion account number' }, { key: 'supportEmail', label: 'Fusion support email', placeholder: 'from your Fusion welcome packet' }, { key: 'portalUser', label: 'Customer portal username (for your reference)' }], envVars: [], docs: 'https://www.fusionconnect.com/customer-support', howTo: ['Fusion Connect does not offer a public API — Omni stores your account and circuit details', 'Enter the support email from your Fusion welcome packet', 'Typing "open fusion ticket …" emails Fusion support with the circuit and site details'] },
]

/** The wider marketplace (adapter slots). Core ones above are fully wired; these are catalogued for the roadmap. */
export const MARKETPLACE: Record<string, string[]> = {
  'AI': ['Claude', 'Microsoft Copilot', 'OpenAI', 'Google Gemini'],
  'RMM': ['NinjaOne', 'Atera', 'Datto RMM', 'ConnectWise Automate', 'Kaseya VSA', 'N-able N-sight', 'Syncro', 'Tactical RMM', 'Level', 'Action1', 'Automox', 'Chocolatey', 'RustDesk', 'ScreenConnect', 'Splashtop'],
  'PSA & Ticketing': ['Zammad', 'ITFlow', 'HaloPSA', 'ConnectWise Manage', 'Autotask', 'Syncro PSA', 'Zendesk', 'Freshdesk', 'Jira Service Management'],
  'Security': ['Huntress', 'SentinelOne', 'CrowdStrike', 'Microsoft Defender', 'Sophos', 'Bitdefender', 'Blackpoint', 'Todyl', 'Proofpoint', 'Mimecast', 'Avanan', 'IronScales', 'DNSFilter', 'Cisco Umbrella', 'KnowBe4', 'Keeper', 'Bitwarden', 'Dark Web ID', 'Liongard', 'RocketCyber'],
  'Microsoft & Identity': ['Microsoft 365', 'Entra ID', 'Entra admin center', 'Windows Server / Active Directory', 'Intune', 'Azure', 'Active Directory (on-prem)', 'Google Workspace', 'Okta', 'Duo'],
  'Networking': ['UniFi', 'Meraki', 'Fortinet', 'SonicWall', 'WatchGuard', 'Aruba', 'Auvik', 'Domotz', 'Lansweeper', 'Fing', 'SNMP', 'Omada', 'Starlink'],
  'Backup': ['Proxmox Backup Server', 'Synology', 'Datto BCDR', 'Veeam', 'Acronis', 'Axcient', 'Cove', 'Backupify', 'Dropsuite'],
  'Finance & Payments': ['QuickBooks Online', 'Xero', 'Stripe', 'Square', 'PayPal', 'GoCardless', 'Bill.com', 'Expensify'],
  'Payroll & HR': ['Gusto', 'QuickBooks Payroll', 'ADP', 'Paychex', 'Rippling', 'Deel'],
  'Distribution & Procurement': ['Pax8', 'Ingram Micro', 'TD SYNNEX', 'D&H', 'Amazon Business', 'CDW', 'Dell Premier', 'Sortly'],
  'CRM & Sales': ['HubSpot', 'Salesforce', 'Zoho CRM', 'Pipedrive', 'PandaDoc', 'DocuSign'],
  'Communication': ['Webex', 'Fusion Connect', 'Slack', 'Microsoft Teams', 'Zoom', 'Twilio', 'Vapi', 'Retell AI', 'ElevenLabs', 'Resend', 'RingCentral', '3CX'],
  'Projects & Docs': ['ClickUp', 'Monday.com', 'Asana', 'Notion', 'IT Glue', 'Hudu', 'Google Drive', 'OneDrive', 'Dropbox', 'SharePoint'],
  'Virtualization & Monitoring': ['Proxmox VE', 'Hyper-V', 'VMware vSphere', 'Uptime Kuma', 'PRTG', 'Zabbix'],
  'Print': ['HP', 'Canon', 'Brother', 'Epson', 'Xerox', 'PaperCut'],
}
export const MARKETPLACE_COUNT = Object.values(MARKETPLACE).reduce((a, l) => a + l.length, 0)
